# Generated by Django 5.0.6 on 2024-07-01 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JJJs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='hostel',
        ),
        migrations.AlterField(
            model_name='hostel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JJJs.area'),
        ),
    ]
